pi*2^3-sqrt(4)
abs(12-7*2/3-9)
factorial(3)
log(3,base=2)
log10(5)
log2(3)
log4(6)
exp(3)
cos(30)
sin(12)
tan(40)
pi()
pi*2^3
pi*3
abs(34)
ls()
ls(pattern='b')
ls(pattern='be')
ls(pattern='l')
rm(list)
ls(pattern='^[be]')
ls(Pattern='^be')
ls(pattern='^b|^e|')
ls(pattern='m$')
history(max.show=12)
save(list,file='filename')
data.frame()
height=c(9,11,13,14,6)
plant=c('valgaris','valgaris','sativa','sativa','sativa')
water=c('lo','lo','mid','hi','hi')
num=c(5,9,8,4,10)
df=data.frame(height,plant,water,num)
df
matrix(df)
ram=c(4,8,9)
shyam=c('ria','mohit','ria')
manoj=c('mi','mi','hi')
num=c(1,2,3)
df=data.frame(ram,shyam,manoj)
getwd()
3+5
savehistory(file= '.rhistory')
loadhistory(file='.rhistory')
save(list,file='kiana')
save(list=mylist,file=C:/Users/selfk/OneDrive/Documents/New folder)
save.image(file='kiana')
write.table(mydata,file='kiana',row.names=TRUE,sep='',col.names TRUE)
city<-c('indore','delhi','bengalore')
city
color<-c('red','yellow','green')
color
class(color)
age<-32
class(age)
mix<-c("red",2,"delhi")
mic
mix
class(mix)
metal<-list('gold','silver','diamond')
metal
metal<-c('gold','silver','diamond')
metal
p<-matrix(c(1,2,3,4,5,6),nrow=2,ncol=3)
p
p<-matrix(list('gold','red',2,4,5,6),nrow=2,ncol=3)
p
a<-array(c(1,2), dim=c(3,3,2))
a
p<-c("p","s","d")
p
length(p)
max(p)
min(p)
r<-c(4,9,8,7,23)
r
max(r)
min(r)
city<-c('indore','delhi','mumbai')
factorcity<-factor(city)
factorcity
print(nlevels(factorcity))
save.image(file='kiana')
library(help="datasets")
getwd()
hist(a$salary,main="table",ylab="age",xlab="salary")
help(stem)
stem(data$age)
help(hist)
colsums(1a,)
a<-c(4,5,8,10,23,5,9)
mean(a)
median(a)
sort(a)
mode(a)
table(a)
names(sort(-table(a)))
names(sort(-table(a)))[1]
data3=scan()
2 3 4 5 6
3 4 5 6 7
data3
data2=scan(sep=',')
2,3,4,5,6
3,6,8,9,0
data2
data4=scan(what='character'())
mon tue wed
thu
fri
data4
data5=scan(sep=',',what='character'())
k d kk 
s
data5
s<-c(1,2,3,4,5,6,7,8)
mean(s)
median(s)
mode(s)
names(sort(-table(a)))[1]
names(sort(-table(a)))[1]
names(sort(-table(a)))[1]
a<-c(3,4,5,6,3)
pie(a)
labels<-c('m','e','g','h','l')
pie(a,labels,main='student marks in different subjects',init.angle =90)
help(mode)
